before_all do
  Dotenv.load ".env.secret"
end

desc "Create App on Developer Portal and App Store Connect"
lane :create_app do
  create_app_online # produce
end

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end

  desc "Sync code signing"
  lane :signing do
    sync_code_signing(
      verbose: true
    )
    
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    signing
    build_ios_app(
      verbose: true
    ) # gym
  end

  desc "Release"
  lane :release do
    build
    upload_to_app_store # deliver
  end
end

lane :init_ci do
  github_action(
    api_token: "3a859b7022f1e10dfd9cf7ecb1acba9308dfb0d4",
    org: "ggndpsingh",
    repo: "LoanCalculator",
    match_org: "ggndpsingh",
    match_repo: "fastlane-match-repo",
    dotenv_paths: ["fastlane/.env.secret"] # optional
  )
end