before_all do
  Dotenv.load ".env.secret"
end

desc "Create App on Developer Portal and App Store Connect"
lane :create_app do
  create_app_online # produce
end

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end

  desc "Sync code signing"
  lane :signing do
    sync_code_signing # match
    
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    signing
    build_ios_app # gym
  end

  desc "Release"
  lane :release do
    build
    upload_to_app_store # deliver
  end
end


platform :mac do
  desc "Sync code signing"
  lane :signing do
    sync_code_signing

  end

  desc "Build binary"
  lane :build do

  end

  desc "Release"
  lane :release do

  end
end

lane :init_ci do
  github_action(
    api_token: "36af7d9743b7a5a367b0211b3d8f4afa9bae1e42",
    org: "ggndpsingh",
    repo: "LoanCalculator",
    dotenv_paths: ["fastlane/.env.secret"] # optional
  )
end