before_all do
  Dotenv.load ".env.secret"
end

desc "Create App on Developer Portal and App Store Connect"
lane :create_app do
  create_app_online # produce
end

platform :ios do
  before_all do
    Dotenv.load ".env.ios"
  end

  desc "Sync code signing"
  lane :signing do
    create_keychain(
      name: "CI",
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )
    match(
      keychain_name: "CI",
      keychain_password: ENV["MATCH_PASSWORD"],
      verbose: true
    )
    
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
    ]
    update_code_signing_settings(
      profile_name: mapping[ENV['MATCH_APP_IDENTIFIER']]
    )
  end

  desc "Build binary"
  lane :build do
    signing
    build_ios_app(
      verbose: true
    ) # gym
  end

  desc "Upload to App Center"
  lane :upload_to_appcenter do
    build

    appcenter_upload(
      api_token: ENV["APP_CENTER_TOKEN"],
      owner_name: "ggndpsingh",
      owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: "LoanCalculator",
      file: "build/ios/LoanCalculator.ipa",
      notify_testers: false # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end

  desc "Release"
  lane :release do
    build
    upload_to_app_store # deliver
  end
end
